version: "3"
services:
  back:
    container_name: english_api
    image: english_api
    build: .
    ports:
      - "8112:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      HOST: 0.0.0.0

  db:
    container_name: english_db
    image: "mysql:8.0.27"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "app"
    ports:
      - "3388:3306"
    volumes:
      - ./docker/data/db-store:/var/lib/mysql
volumes:
  db-store:
